apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
type: Opaque
data:
  TZ: ${TIMEZONE}
  HF_ENDPOINT: ${HF_ENDPOINT}
  MACOS: ${MACOS}
  node.name: opensearch01
  ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
  bootstrap.memory_lock: false
  discovery.type: single-node
  xpack.security.enabled: true
  xpack.security.http.ssl.enabled: false
  xpack.security.transport.ssl.enabled: false
  cluster.routing.allocation.disk.watermark.low: 5gb
  cluster.routing.allocation.disk.watermark.high: 3gb
  cluster.routing.allocation.disk.watermark.flood_stage: 2gb
  OPENSEARCH_PASSWORD: ${OPENSEARCH_PASSWORD}
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_PASSWORD}
  plugins.security.disabled: false
  plugins.security.ssl.http.enabled: false
  plugins.security.ssl.transport.enabled: true
  http.port: 9201
  SANDBOX_EXECUTOR_MANAGER_POOL_SIZE: ${SANDBOX_EXECUTOR_MANAGER_POOL_SIZE:-3}
  SANDBOX_BASE_PYTHON_IMAGE: ${SANDBOX_BASE_PYTHON_IMAGE:-infiniflow/sandbox-base-python:latest}
  SANDBOX_BASE_NODEJS_IMAGE: ${SANDBOX_BASE_NODEJS_IMAGE:-infiniflow/sandbox-base-nodejs:latest}
  SANDBOX_ENABLE_SECCOMP: ${SANDBOX_ENABLE_SECCOMP:-false}
  SANDBOX_MAX_MEMORY: ${SANDBOX_MAX_MEMORY:-256m}
  SANDBOX_TIMEOUT: ${SANDBOX_TIMEOUT:-10s}
  MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
  MINIO_ROOT_USER: ${MINIO_USER}
  MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
