apiVersion: v1
kind: Service
metadata:
  name: ragflow
spec:
  ports:
  - port: 9380
    targetPort: 9380
  - port: 80
    targetPort: 80
  - port: 443
    targetPort: 443
  - port: 5678
    targetPort: 5678
  - port: 5679
    targetPort: 5679
  - port: 9382
    targetPort: 9382
  selector:
    app: ragflow
